/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "point.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Point, Point, AUTO)


PB_BIND(Points, Points, 2)


PB_BIND(PointArray, PointArray, 4)



